# Generated by Django 3.2.6 on 2021-11-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professeurs',
            fields=[
                ('profId', models.AutoField(primary_key=True, serialize=False)),
                ('experience', models.IntegerField()),
                ('orgId', models.IntegerField()),
                ('fonction', models.CharField(max_length=255)),
                ('nomme', models.CharField(max_length=5)),
                ('tempprio', models.CharField(max_length=5)),
                ('tempor', models.CharField(max_length=5)),
                ('CAD', models.CharField(max_length=3)),
                ('CADFrom', models.DateField()),
                ('CADTo', models.DateField()),
            ],
        ),
    ]
