# Generated by Django 3.2.6 on 2021-11-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='professeurs',
            table='professeurs',
        ),
    ]
